name: geometric
dependencies:
  - python=3.7
  - pip
  #- gensim
  #- networkx
  - jupyter    # for use in Jupyter notebook
  - ipykernel   # for recognition of conda env in Jupyter notebook
  #- pip:
  #  - torch==1.13.0
